version: '3.4'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd

  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}gelosapi
    build: 
      context: .
      dockerfile: Gelos.API/Dockerfile

volumes:
  dbdata: 
    driver: local