name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Change Directory
      run: cd Gelos
    - name: Restore dependencies
      run: dotnet restore Gelos/Gelos.sln
    - name: Build
      run: dotnet build Gelos/Gelos.sln --no-restore 
    - name: Test
      run: dotnet test Gelos/Gelos.sln --no-build --verbosity normal
